schema_version: 1

context:
  name: shandy-sqlfmt
  version: 0.30.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/shandy_sqlfmt-${{ version }}.tar.gz
  sha256: 1572295da093d8577eb75b1eb17d7cc0b2929d00a72e30ca5369645d0265de60

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sqlfmt = sqlfmt.cli:sqlfmt
      - sqlfmt_primer = sqlfmt_primer.primer:sqlfmt_primer

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - jinja2 >=3.0,<4
    - python >=${{ python_min }}
    - click >=8.0,<9
    - tqdm >=4.67,<5
    - platformdirs >=2.4,<5.0
    - tomli >=2.0,<3
  run_constraints:
    - black *
    - gitpython >=3.1.24,<4.0.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - sqlfmt
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - sqlfmt --help

about:
  summary: sqlfmt is an opinionated CLI tool that formats your sql files
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://sqlfmt.com

extra:
  recipe-maintainers:
    - xhochy
